#!/bin/bash

# Ubuntu/Debian Update Tool (Version 1.0)
# Command to fully update the system: "update". (June, 2020)
# By Voltage (GNU/General Public License version 3.0)

# Color:
LIGHTGREEN='\x1b[1;32m'
YELLOW='\x1b[1;33m'
LIGHTRED='\x1b[1;31m'
TURQUOISE='\x1b[0;36m'
LIGHTBLUE='\x1b[1;34m'
RESET='\x1B[0m'
NORMAL='\x1b[1;37m'


# Set BASH to quit script and exit on errors:

set -e

# Functions:


update() {

echo -e "${LIGHTGREEN}Starting system update...${RESET}"
sudo apt-get update | sudo apt-get upgrade | sudo apt-get full-upgrade | sudo apt-get dist-upgrade | sudo apt-get autoremove | sudo apt-get autoclean 

}

close() {

echo -e "\n\n---------------------------"
echo -e "- ${LIGHTGREEN}System Update Complete!${RESET} -"
echo -e "---------------------------"
exit

}

help() {
 
echo -e "Update is a tool that automates updating the system procedure for Ubuntu and Debian based on Linux systems." 
echo -e "\nCommands:" 
echo -e "	${LIGHTGREEN}update${RESET} = System Update. It will update the apt chache and then perform a completely system update." 
echo -e "	${LIGHTGREEN}update --help${RESET} = shows this help page." 
echo -e "\n${TURQUOISE}By Voltage (GNU/General Public License version 3.0 ${RESET}/n"

}

# Execution.

# What is this tool:

echo -e "\n${LIGHTBLUE}Ubuntu/Debian Auto-Update (Version 1.0)${RESET}\n\n"

# Help

if [ "$1" == "--help" ]; then
	help
	exit
fi

# Check for invalid argument

if [ -n "$1"  ]; then
	echo -e "${LIGHTRED}Error: Invalid argument. Try 'update --help' for more info.${RESET}" >&2
	exit 1
fi

# Update

update
close
